version: '3.8'

services:
  db:
    image: postgres:15.1
    volumes:
      - 'db_1:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./doc/:/doc
    environment:
      SWAGGER_JSON: /doc/openapi.yaml
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - './api:/myapp'
      - './doc:/myapp/doc'
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BASE_URL: ${BASE_URL}
    tty: true
    stdin_open: true
    depends_on:
      - db
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - './client:/usr/src/app'
    tty: true
    stdin_open: true

volumes:
  db_1:
