version: '3.8'

services:
  db:
    image: postgres:15.1
    volumes:
      - 'db_1:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - './api:/myapp'
      - './nginx:/myapp/nginx'
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    tty: true
    stdin_open: true
    depends_on:
      - db
  nginx:
    image: nginx:1.23.2
    ports:
      - '80:80'
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/swagger-ui:/usr/share/nginx/html/swagger-ui
    depends_on:
      - api
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - './client:/usr/src/app'
    tty: true
    stdin_open: true

volumes:
  db_1:
