inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Documentation:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/Rails/InferredSpecType:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Rails/FilePath:
  Enabled: false
